### ISSUE TITLE
mincost_flow() example code

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [JuliaGraphs/LightGraphsFlows.jl#12]
The example in mincost.jl calls `ClpSolver()`.  Would recommend adding
`using Clp`
to the example with a note about how you can use any solver.  It's easy for a novice like me to install LightGraphsFlows and use the `maximum_flow()` code, but the `mincost_flow()` example code fails out of the box.

**Comment by matbesancon** [comment]
hi,
you're right this is lacking in the README + doc, I'll add a precision on this point thanks

**Comment by Jacob-Stevens-Haas** [comment]
Thanks!

Although, question about options.  I came here looking for a specialized minimum cost flow algorithms, such as Network Simplex.  Does the implementation by passing to `MathProgBrase` and `ClpSolver()` strip that extra structure from the problem?
