### ISSUE TITLE
Switch MathProgBase for MathOptInterface.jl

### ISSUE THREAD

**Issue by matbesancon** [JuliaGraphs/LightGraphsFlows.jl#16]
As recommended by the JuliaOpt org, MathProgBase is going to be changed for MathOptInterface, we're going to do it once many solvers have switched

**Comment by rschwarz** [comment]
I don't think there is a simple `linprog` anymore in MathOptInterface. Maybe it makes sense to switch to JuMP instead?

**Comment by matbesancon** [comment]
indeed why not, I'm not sure this is still the right time, MPB is still fine for the use cases of flow algorithms for the moment, users might have JuMP 0.18 for callbacks and other stuff

**Comment by mlubin** [comment]
JuMP provides a simpler interface than MathOptInterface if all you want to do is the equivalent of `linprog`. I would recommend starting to think about the switch. MathProgBase is being maintained on a minimal-effort basis at this point (i.e., if something broken requires more than minimal effort to fix, we probably won't do it).

**Comment by matbesancon** [comment]
yes I agree, this will also avoid the whole gymnastic of flattening the flow matrix into an array

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
