### ISSUE TITLE
Incorrect MinCut result

### ISSUE THREAD

**Issue by etiennedeg** [JuliaGraphs/LightGraphsFlows.jl#27]
Hi, 
mincut seems to return false result with this graph:
![graphe](https://user-images.githubusercontent.com/22714764/64792711-241b3500-d57a-11e9-8b98-05c14c2d8ce3.png)
Non-labeled edges have infinite capacity
edges 1-2, 4-7, 5-7 and 6-7 are saturated after the running of the algorithm

Output:
`[1, 3, 6, 5]
[2, 4, 7]
3.0`
Expected Output
`[1, 2, 3, 4, 5, 6]
[7]
3.0`

The algorithm should find every reachable node from the source by a flow, it instead reaches nodes reachable by non saturated direct edges

How to reproduce:
```
flow_graph = lg.DiGraph(7)
capacity_matrix = zeros(7,7)
flow_edges = [
(1,2,2),(1,3,2),(2,4,4),(2,5,4),
(3,5,4),(3,6,4),(4,7,1),(5,7,1),(6,7,1)
]
for e in flow_edges
    u, v, f = e
    lg.add_edge!(flow_graph, u, v)
    capacity_matrix[u,v] = f
end
a,b,c= LightGraphsFlows.mincut(flow_graph, 1, 7, capacity_matrix, EdmondsKarpAlgorithm())
println(a)
println(b)
println(c)
```

**Comment by etiennedeg** [comment]
I made a PR : [#32](https://github.com/JuliaGraphs/LightGraphsFlows.jl/pull/32)

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
