### ISSUE TITLE
Error while computing the st min cut

### ISSUE THREAD

**Issue by mathieuLacroix** [JuliaGraphs/LightGraphsFlows.jl#33]
Hi, 

The computation of the vertex set `part1` in the `mincut` function defined in LightGraphsFlows is incorrect as it may contain multiple copies of a same node. The problem occurs for instance with the following example:
```julia
 g = CompleteDiGraph(10)
cap1 = [
            0.0  10.0   0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0;
           10.0   0.0   1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0;
            0.0   1.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  2.0;
            0.0   0.0   0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0;
            0.0   0.0   0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0;
            0.0   0.0   0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0;
            1.0   0.0   0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0;
            0.0   1.0   0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0;
            0.0   0.0   0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0;
            1.0   0.0   2.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
       ]
(part1, part2, value) = LightGraphsFlows.mincut(g,1,10,cap1,LightGraphsFlows.PushRelabelAlgorithm())
```
Running the previous code gives a vertex set `part1` containing twice node 2.

I think that the problem comes from the computation of `dests` when computing the minimum cut.
Instead of
```julia
[dst for dst in 1:lg.nv(flow_graph) if residual_matrix[node,dst]>0.0 && dst ∉ part1]
```
shouldn't we have
```julia
[dst for dst in 1:lg.nv(flow_graph) if residual_matrix[node,dst]>0.0 && dst ∉ part1 && dst ∉ queue]
```
since every node in the queue is then added to `part1`?

Best, 
Mathieu

**Comment by etiennedeg** [comment]
It is related to [#27](https://github.com/JuliaGraphs/LightGraphsFlows.jl/issues/27)
I made a PR, but it is not merged yet.

**Comment by matbesancon** [comment]
I think this now works with the fixed PR, a release will be out soon

**Comment by matbesancon** [comment]
I just tested, working correctly, closing now

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
